
cxx_library(
  name = 'foundation',
  exported_headers = subdir_glob([
    ('repo/include', '**/*.hpp'),
  ]),
  srcs = glob([
    'repo/source/*.cpp'
  ]),
  platform_compiler_flags = [
    ('.x86_64$', {'/EHsc'}),
  ],
  visibility = [
    'PUBLIC',
  ]
)
