prebuilt_cxx_library(
  name = 'foundation',
  header_only = True,
  exported_headers  = subdir_glob([     # public include files
    ('repo/include', '**/*.hpp'),       # those will be exported,
  ]),
  visibility = [
    'PUBLIC',
  ]
)
