cxx_library(
  name = 'framework',
  #header_namespace = 'framework',
  srcs = glob([
    'repo/src/**/*.cpp',
  ]),
  headers = subdir_glob([                 
    ('repo/detail', '**/*.h'),            
    ('repo/detail', '**/*.hpp'),
  ]),
  exported_headers = subdir_glob([
    ('repo/include', '**/*.h'),  
    ('repo/include', '**/*.hpp'),
  ]),
  exported_deps = [
    '//foundation:foundation',
    '//cppzmq:cppzmq',
    '//libzmq:libzmq'
  ],
  visibility = [
    'PUBLIC'
  ]
)
