prebuilt_cxx_library(
  name = 'cppzmq',
  header_only = True,
  header_namespace = '',
  exported_headers  = subdir_glob([
    ('repo', '**/*.hpp'),
  ]),
  exported_deps = [
    '//libzmq:libzmq'
  ],
  visibility = [
    'PUBLIC',
  ]
)
