
prebuilt_cxx_library(
  name = 'cpp-stateless',
  header_only = True,
  header_namespace = 'stateless++',
  exported_headers  = subdir_glob([ # public include files
    ('repo/stateless++', '**/*.h'), # those will be exported
    ('repo/stateless++', '**/*.hpp'), # those will be exported,
  ]),
  visibility = [
    'PUBLIC',
  ]
)
